### ISSUE TITLE
Swift 3 please

### ISSUE THREAD

**Issue by magonicolas** [iluuu1994/Pathfinder#1]
Hello there! I really need to implement this! Can you update it to swift 3 please? or maybe help me with a basic project, I need to do something like this: https://dl.dropboxusercontent.com/u/24078452/Screen%20Shot%202017-01-10%20at%2011.49.17%20PM.png

**Comment by iluuu1994** [comment]
You posted a screenshot from [Apple's website](https://developer.apple.com/library/content/documentation/General/Conceptual/GameplayKit_Guide/Pathfinding.html). Why don't you just use Apple's pathfinder component? [Here is some sample code](https://developer.apple.com/library/content/samplecode/Pathfinder_GameplayKit/Introduction/Intro.html#//apple_ref/doc/uid/TP40016461). Sorry dude, no one will write your code for you 😉

**Comment by iluuu1994** [comment]
Also, since Apple now has it's own pathfinder component I won't update this one anymore.
